### ISSUE TITLE
Mixup between versions of BSD licenses

### ISSUE THREAD

**Issue by rpavlik** [holtwick/what-license.com#2]
I pasted in the license from here: https://github.com/ValveSoftware/openvr/blob/master/LICENSE  and it did show a pretty high match, calling it BSD license. However, when I clicked on the link, it took me to the OSI's page for the [2-clause BSD license](http://opensource.org/licenses/bsd-license), while the text in the "ranking of best matches" showed it matched against the [3-clause](http://opensource.org/licenses/BSD-3-Clause) (because that's what it is) - you can actually see the third clause in the search results.

(By the way - thanks for this app, it's super helpful, the kind of thing I've been looking for and putting off writing myself :+1: )

**Comment by holtwick** [comment]
I think your pull request fixed that?
